"""add column "seen" 

Revision ID: 3e27e454ffcb
Revises: 335ba49a266f
Create Date: 2020-11-05 00:49:14.937064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e27e454ffcb'
down_revision = '335ba49a266f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('currentquestions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.drop_constraint('questions_student_id_fkey', 'questions', type_='foreignkey')
    op.drop_column('questions', 'student_id')
    op.drop_column('questions', 'answer')
    op.add_column('students', sa.Column('questions', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'questions')
    op.add_column('questions', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('questions_student_id_fkey', 'questions', 'students', ['student_id'], ['student_id'])
    op.drop_table('currentquestions')
    op.drop_table('answers')
    op.drop_table('admins')
    # ### end Alembic commands ###
