"""add column "seen" 

Revision ID: de909d1622b9
Revises: 8fcb20f6ae54
Create Date: 2020-11-03 09:00:32.145552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de909d1622b9'
down_revision = '8fcb20f6ae54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'seen')
    # ### end Alembic commands ###
